# Generated by Django 4.1.1 on 2022-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('XR', 'Xorazm'), ('TH', 'Toshkent'), ('SM', 'Samarqand')], default='XR', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('oliy', 'Oliy'), ('1_toifa', '1-toifa'), ('2_toifa', '1-toifa')], default='2_toifa', max_length=10),
        ),
    ]
